sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Hqcry91lASshtb/Yxy+Lhow3QcOvh0AdR31YCGx9Z006SPlNTiyp1LXp4eL8oVIDzMScCvDkEfkPonD8/Lkv9gzHGnujx6FlDhwffwJtVyk8z9ckQSA6RXRLcAQpBkViYGpIYw7KOsm8eokuFI/1+8UPAGrZrnSR3WeyRKKhvrxzf8oOpl3zFPZfdAAyWTXErB1rWCp4VbD4Z6uJ4OEoG7F+Kjm6yuBgpCOHrQSkxw/uP+SaPcDs71/hNSdw/JKCoAYM+DpGrPlm85T8YaqtsCZNS2ElFDqPkLg771wyRpAtRKZpAZWERf0cqw6880MlJ/v6DwZ9rWxbiInEJMbfdz0rDIV3G6dVdVrRVJ9dEZFfJtryy2+mis8izEFr4MrXy0P7LO6jg5TNfpZpH+QqrW/hPa8ihzBPxItzEM348oV7eVlzb8CUWpdofsjGT5O26CL+VE85SD+OC5FBEL+4nQe/MIy0AePkNlQ5KkgYmLA40ovXrRcJHW1J6tNvKAZj9qPs6r2eal8eJnJTYenv/7EOCEzE/BeTEzvqxLzSS3z7rx5PZ84Fe/XwKRRCo+E6K+jWJLzNmxkvmUTAM58WBIuzdmHK9sLKUIh9fI/6J0Uk2KveqD1h6ENfai6BmhEIyb/rB59uk4WOe3FiMF14lAuSLjHN/B8FGzGPi2L0yDA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Madam-How-and-Lady-Why--Or-First-Lessons-in-Earth-Lore-for-Children_1697
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy